//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TEST_DESKTOPModel", "FK__QuanLiCaL__IDNha__173876EA", "NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Test_Desktop.NhanVien), "QuanLiCaLam", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test_Desktop.QuanLiCaLam), true)]

#endregion

namespace Test_Desktop
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NhanVienEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NhanVienEntities object using the connection string found in the 'NhanVienEntities' section of the application configuration file.
        /// </summary>
        public NhanVienEntities() : base("name=NhanVienEntities", "NhanVienEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NhanVienEntities object.
        /// </summary>
        public NhanVienEntities(string connectionString) : base(connectionString, "NhanVienEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NhanVienEntities object.
        /// </summary>
        public NhanVienEntities(EntityConnection connection) : base(connection, "NhanVienEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DanhGiaSach> DanhGiaSach
        {
            get
            {
                if ((_DanhGiaSach == null))
                {
                    _DanhGiaSach = base.CreateObjectSet<DanhGiaSach>("DanhGiaSach");
                }
                return _DanhGiaSach;
            }
        }
        private ObjectSet<DanhGiaSach> _DanhGiaSach;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MuonTraSach> MuonTraSach
        {
            get
            {
                if ((_MuonTraSach == null))
                {
                    _MuonTraSach = base.CreateObjectSet<MuonTraSach>("MuonTraSach");
                }
                return _MuonTraSach;
            }
        }
        private ObjectSet<MuonTraSach> _MuonTraSach;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NguoiDung> NguoiDung
        {
            get
            {
                if ((_NguoiDung == null))
                {
                    _NguoiDung = base.CreateObjectSet<NguoiDung>("NguoiDung");
                }
                return _NguoiDung;
            }
        }
        private ObjectSet<NguoiDung> _NguoiDung;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhanVien> NhanVien
        {
            get
            {
                if ((_NhanVien == null))
                {
                    _NhanVien = base.CreateObjectSet<NhanVien>("NhanVien");
                }
                return _NhanVien;
            }
        }
        private ObjectSet<NhanVien> _NhanVien;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuanLiCaLam> QuanLiCaLam
        {
            get
            {
                if ((_QuanLiCaLam == null))
                {
                    _QuanLiCaLam = base.CreateObjectSet<QuanLiCaLam>("QuanLiCaLam");
                }
                return _QuanLiCaLam;
            }
        }
        private ObjectSet<QuanLiCaLam> _QuanLiCaLam;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sach> Sach
        {
            get
            {
                if ((_Sach == null))
                {
                    _Sach = base.CreateObjectSet<Sach>("Sach");
                }
                return _Sach;
            }
        }
        private ObjectSet<Sach> _Sach;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaiKhoan> TaiKhoan
        {
            get
            {
                if ((_TaiKhoan == null))
                {
                    _TaiKhoan = base.CreateObjectSet<TaiKhoan>("TaiKhoan");
                }
                return _TaiKhoan;
            }
        }
        private ObjectSet<TaiKhoan> _TaiKhoan;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DanhGiaSach EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDanhGiaSach(DanhGiaSach danhGiaSach)
        {
            base.AddObject("DanhGiaSach", danhGiaSach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MuonTraSach EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMuonTraSach(MuonTraSach muonTraSach)
        {
            base.AddObject("MuonTraSach", muonTraSach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NguoiDung EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNguoiDung(NguoiDung nguoiDung)
        {
            base.AddObject("NguoiDung", nguoiDung);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanVien EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanVien(NhanVien nhanVien)
        {
            base.AddObject("NhanVien", nhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuanLiCaLam EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuanLiCaLam(QuanLiCaLam quanLiCaLam)
        {
            base.AddObject("QuanLiCaLam", quanLiCaLam);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sach EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSach(Sach sach)
        {
            base.AddObject("Sach", sach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaiKhoan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaiKhoan(TaiKhoan taiKhoan)
        {
            base.AddObject("TaiKhoan", taiKhoan);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="DanhGiaSach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DanhGiaSach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DanhGiaSach object.
        /// </summary>
        /// <param name="maDanhGia">Initial value of the MaDanhGia property.</param>
        public static DanhGiaSach CreateDanhGiaSach(global::System.Int32 maDanhGia)
        {
            DanhGiaSach danhGiaSach = new DanhGiaSach();
            danhGiaSach.MaDanhGia = maDanhGia;
            return danhGiaSach;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaDanhGia
        {
            get
            {
                return _MaDanhGia;
            }
            set
            {
                if (_MaDanhGia != value)
                {
                    OnMaDanhGiaChanging(value);
                    ReportPropertyChanging("MaDanhGia");
                    _MaDanhGia = StructuralObject.SetValidValue(value, "MaDanhGia");
                    ReportPropertyChanged("MaDanhGia");
                    OnMaDanhGiaChanged();
                }
            }
        }
        private global::System.Int32 _MaDanhGia;
        partial void OnMaDanhGiaChanging(global::System.Int32 value);
        partial void OnMaDanhGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDNguoiDung
        {
            get
            {
                return _IDNguoiDung;
            }
            set
            {
                OnIDNguoiDungChanging(value);
                ReportPropertyChanging("IDNguoiDung");
                _IDNguoiDung = StructuralObject.SetValidValue(value, "IDNguoiDung");
                ReportPropertyChanged("IDNguoiDung");
                OnIDNguoiDungChanged();
            }
        }
        private Nullable<global::System.Int32> _IDNguoiDung;
        partial void OnIDNguoiDungChanging(Nullable<global::System.Int32> value);
        partial void OnIDNguoiDungChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDSach
        {
            get
            {
                return _IDSach;
            }
            set
            {
                OnIDSachChanging(value);
                ReportPropertyChanging("IDSach");
                _IDSach = StructuralObject.SetValidValue(value, "IDSach");
                ReportPropertyChanged("IDSach");
                OnIDSachChanged();
            }
        }
        private Nullable<global::System.Int32> _IDSach;
        partial void OnIDSachChanging(Nullable<global::System.Int32> value);
        partial void OnIDSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DiemDanhGia
        {
            get
            {
                return _DiemDanhGia;
            }
            set
            {
                OnDiemDanhGiaChanging(value);
                ReportPropertyChanging("DiemDanhGia");
                _DiemDanhGia = StructuralObject.SetValidValue(value, "DiemDanhGia");
                ReportPropertyChanged("DiemDanhGia");
                OnDiemDanhGiaChanged();
            }
        }
        private Nullable<global::System.Int32> _DiemDanhGia;
        partial void OnDiemDanhGiaChanging(Nullable<global::System.Int32> value);
        partial void OnDiemDanhGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NhanXet
        {
            get
            {
                return _NhanXet;
            }
            set
            {
                OnNhanXetChanging(value);
                ReportPropertyChanging("NhanXet");
                _NhanXet = StructuralObject.SetValidValue(value, true, "NhanXet");
                ReportPropertyChanged("NhanXet");
                OnNhanXetChanged();
            }
        }
        private global::System.String _NhanXet;
        partial void OnNhanXetChanging(global::System.String value);
        partial void OnNhanXetChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="MuonTraSach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MuonTraSach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MuonTraSach object.
        /// </summary>
        /// <param name="iDMuonTra">Initial value of the IDMuonTra property.</param>
        public static MuonTraSach CreateMuonTraSach(global::System.Int32 iDMuonTra)
        {
            MuonTraSach muonTraSach = new MuonTraSach();
            muonTraSach.IDMuonTra = iDMuonTra;
            return muonTraSach;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMuonTra
        {
            get
            {
                return _IDMuonTra;
            }
            set
            {
                if (_IDMuonTra != value)
                {
                    OnIDMuonTraChanging(value);
                    ReportPropertyChanging("IDMuonTra");
                    _IDMuonTra = StructuralObject.SetValidValue(value, "IDMuonTra");
                    ReportPropertyChanged("IDMuonTra");
                    OnIDMuonTraChanged();
                }
            }
        }
        private global::System.Int32 _IDMuonTra;
        partial void OnIDMuonTraChanging(global::System.Int32 value);
        partial void OnIDMuonTraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDNguoiDung
        {
            get
            {
                return _IDNguoiDung;
            }
            set
            {
                OnIDNguoiDungChanging(value);
                ReportPropertyChanging("IDNguoiDung");
                _IDNguoiDung = StructuralObject.SetValidValue(value, "IDNguoiDung");
                ReportPropertyChanged("IDNguoiDung");
                OnIDNguoiDungChanged();
            }
        }
        private Nullable<global::System.Int32> _IDNguoiDung;
        partial void OnIDNguoiDungChanging(Nullable<global::System.Int32> value);
        partial void OnIDNguoiDungChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDSach
        {
            get
            {
                return _IDSach;
            }
            set
            {
                OnIDSachChanging(value);
                ReportPropertyChanging("IDSach");
                _IDSach = StructuralObject.SetValidValue(value, "IDSach");
                ReportPropertyChanged("IDSach");
                OnIDSachChanged();
            }
        }
        private Nullable<global::System.Int32> _IDSach;
        partial void OnIDSachChanging(Nullable<global::System.Int32> value);
        partial void OnIDSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true, "HoTen");
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSach
        {
            get
            {
                return _TenSach;
            }
            set
            {
                OnTenSachChanging(value);
                ReportPropertyChanging("TenSach");
                _TenSach = StructuralObject.SetValidValue(value, true, "TenSach");
                ReportPropertyChanged("TenSach");
                OnTenSachChanged();
            }
        }
        private global::System.String _TenSach;
        partial void OnTenSachChanging(global::System.String value);
        partial void OnTenSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayMuon
        {
            get
            {
                return _NgayMuon;
            }
            set
            {
                OnNgayMuonChanging(value);
                ReportPropertyChanging("NgayMuon");
                _NgayMuon = StructuralObject.SetValidValue(value, "NgayMuon");
                ReportPropertyChanged("NgayMuon");
                OnNgayMuonChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayMuon;
        partial void OnNgayMuonChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayMuonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayTraDuKien
        {
            get
            {
                return _NgayTraDuKien;
            }
            set
            {
                OnNgayTraDuKienChanging(value);
                ReportPropertyChanging("NgayTraDuKien");
                _NgayTraDuKien = StructuralObject.SetValidValue(value, "NgayTraDuKien");
                ReportPropertyChanged("NgayTraDuKien");
                OnNgayTraDuKienChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayTraDuKien;
        partial void OnNgayTraDuKienChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayTraDuKienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayTraThucTe
        {
            get
            {
                return _NgayTraThucTe;
            }
            set
            {
                OnNgayTraThucTeChanging(value);
                ReportPropertyChanging("NgayTraThucTe");
                _NgayTraThucTe = StructuralObject.SetValidValue(value, "NgayTraThucTe");
                ReportPropertyChanged("NgayTraThucTe");
                OnNgayTraThucTeChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayTraThucTe;
        partial void OnNgayTraThucTeChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayTraThucTeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoTienPhatSinh
        {
            get
            {
                return _SoTienPhatSinh;
            }
            set
            {
                OnSoTienPhatSinhChanging(value);
                ReportPropertyChanging("SoTienPhatSinh");
                _SoTienPhatSinh = StructuralObject.SetValidValue(value, "SoTienPhatSinh");
                ReportPropertyChanged("SoTienPhatSinh");
                OnSoTienPhatSinhChanged();
            }
        }
        private Nullable<global::System.Int32> _SoTienPhatSinh;
        partial void OnSoTienPhatSinhChanging(Nullable<global::System.Int32> value);
        partial void OnSoTienPhatSinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TinhTrang
        {
            get
            {
                return _TinhTrang;
            }
            set
            {
                OnTinhTrangChanging(value);
                ReportPropertyChanging("TinhTrang");
                _TinhTrang = StructuralObject.SetValidValue(value, true, "TinhTrang");
                ReportPropertyChanged("TinhTrang");
                OnTinhTrangChanged();
            }
        }
        private global::System.String _TinhTrang;
        partial void OnTinhTrangChanging(global::System.String value);
        partial void OnTinhTrangChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="NguoiDung")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NguoiDung : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NguoiDung object.
        /// </summary>
        /// <param name="iDNguoiDung">Initial value of the IDNguoiDung property.</param>
        public static NguoiDung CreateNguoiDung(global::System.Int32 iDNguoiDung)
        {
            NguoiDung nguoiDung = new NguoiDung();
            nguoiDung.IDNguoiDung = iDNguoiDung;
            return nguoiDung;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDNguoiDung
        {
            get
            {
                return _IDNguoiDung;
            }
            set
            {
                if (_IDNguoiDung != value)
                {
                    OnIDNguoiDungChanging(value);
                    ReportPropertyChanging("IDNguoiDung");
                    _IDNguoiDung = StructuralObject.SetValidValue(value, "IDNguoiDung");
                    ReportPropertyChanged("IDNguoiDung");
                    OnIDNguoiDungChanged();
                }
            }
        }
        private global::System.Int32 _IDNguoiDung;
        partial void OnIDNguoiDungChanging(global::System.Int32 value);
        partial void OnIDNguoiDungChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true, "HoTen");
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true, "GioiTinh");
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lop
        {
            get
            {
                return _Lop;
            }
            set
            {
                OnLopChanging(value);
                ReportPropertyChanging("Lop");
                _Lop = StructuralObject.SetValidValue(value, true, "Lop");
                ReportPropertyChanged("Lop");
                OnLopChanged();
            }
        }
        private global::System.String _Lop;
        partial void OnLopChanging(global::System.String value);
        partial void OnLopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChuyenNganh
        {
            get
            {
                return _ChuyenNganh;
            }
            set
            {
                OnChuyenNganhChanging(value);
                ReportPropertyChanging("ChuyenNganh");
                _ChuyenNganh = StructuralObject.SetValidValue(value, true, "ChuyenNganh");
                ReportPropertyChanged("ChuyenNganh");
                OnChuyenNganhChanged();
            }
        }
        private global::System.String _ChuyenNganh;
        partial void OnChuyenNganhChanging(global::System.String value);
        partial void OnChuyenNganhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="NhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhanVien object.
        /// </summary>
        /// <param name="iDNhanVien">Initial value of the IDNhanVien property.</param>
        public static NhanVien CreateNhanVien(global::System.Int32 iDNhanVien)
        {
            NhanVien nhanVien = new NhanVien();
            nhanVien.IDNhanVien = iDNhanVien;
            return nhanVien;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDNhanVien
        {
            get
            {
                return _IDNhanVien;
            }
            set
            {
                if (_IDNhanVien != value)
                {
                    OnIDNhanVienChanging(value);
                    ReportPropertyChanging("IDNhanVien");
                    _IDNhanVien = StructuralObject.SetValidValue(value, "IDNhanVien");
                    ReportPropertyChanged("IDNhanVien");
                    OnIDNhanVienChanged();
                }
            }
        }
        private global::System.Int32 _IDNhanVien;
        partial void OnIDNhanVienChanging(global::System.Int32 value);
        partial void OnIDNhanVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true, "HoTen");
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true, "GioiTinh");
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChucVu
        {
            get
            {
                return _ChucVu;
            }
            set
            {
                OnChucVuChanging(value);
                ReportPropertyChanging("ChucVu");
                _ChucVu = StructuralObject.SetValidValue(value, true, "ChucVu");
                ReportPropertyChanged("ChucVu");
                OnChucVuChanged();
            }
        }
        private global::System.String _ChucVu;
        partial void OnChucVuChanging(global::System.String value);
        partial void OnChucVuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgaySinh
        {
            get
            {
                return _NgaySinh;
            }
            set
            {
                OnNgaySinhChanging(value);
                ReportPropertyChanging("NgaySinh");
                _NgaySinh = StructuralObject.SetValidValue(value, "NgaySinh");
                ReportPropertyChanged("NgaySinh");
                OnNgaySinhChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgaySinh;
        partial void OnNgaySinhChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaySinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiThieu
        {
            get
            {
                return _GioiThieu;
            }
            set
            {
                OnGioiThieuChanging(value);
                ReportPropertyChanging("GioiThieu");
                _GioiThieu = StructuralObject.SetValidValue(value, true, "GioiThieu");
                ReportPropertyChanged("GioiThieu");
                OnGioiThieuChanged();
            }
        }
        private global::System.String _GioiThieu;
        partial void OnGioiThieuChanging(global::System.String value);
        partial void OnGioiThieuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayNhanViec
        {
            get
            {
                return _NgayNhanViec;
            }
            set
            {
                OnNgayNhanViecChanging(value);
                ReportPropertyChanging("NgayNhanViec");
                _NgayNhanViec = StructuralObject.SetValidValue(value, "NgayNhanViec");
                ReportPropertyChanged("NgayNhanViec");
                OnNgayNhanViecChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayNhanViec;
        partial void OnNgayNhanViecChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayNhanViecChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEST_DESKTOPModel", "FK__QuanLiCaL__IDNha__173876EA", "QuanLiCaLam")]
        public EntityCollection<QuanLiCaLam> QuanLiCaLam
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QuanLiCaLam>("TEST_DESKTOPModel.FK__QuanLiCaL__IDNha__173876EA", "QuanLiCaLam");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QuanLiCaLam>("TEST_DESKTOPModel.FK__QuanLiCaL__IDNha__173876EA", "QuanLiCaLam", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="QuanLiCaLam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuanLiCaLam : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuanLiCaLam object.
        /// </summary>
        /// <param name="iDCa">Initial value of the IDCa property.</param>
        /// <param name="sTTCa">Initial value of the STTCa property.</param>
        /// <param name="ngay">Initial value of the Ngay property.</param>
        /// <param name="gioKetThuc">Initial value of the GioKetThuc property.</param>
        /// <param name="gioBatDau">Initial value of the GioBatDau property.</param>
        public static QuanLiCaLam CreateQuanLiCaLam(global::System.Int32 iDCa, global::System.Int32 sTTCa, global::System.DateTime ngay, global::System.TimeSpan gioKetThuc, global::System.TimeSpan gioBatDau)
        {
            QuanLiCaLam quanLiCaLam = new QuanLiCaLam();
            quanLiCaLam.IDCa = iDCa;
            quanLiCaLam.STTCa = sTTCa;
            quanLiCaLam.Ngay = ngay;
            quanLiCaLam.GioKetThuc = gioKetThuc;
            quanLiCaLam.GioBatDau = gioBatDau;
            return quanLiCaLam;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCa
        {
            get
            {
                return _IDCa;
            }
            set
            {
                if (_IDCa != value)
                {
                    OnIDCaChanging(value);
                    ReportPropertyChanging("IDCa");
                    _IDCa = StructuralObject.SetValidValue(value, "IDCa");
                    ReportPropertyChanged("IDCa");
                    OnIDCaChanged();
                }
            }
        }
        private global::System.Int32 _IDCa;
        partial void OnIDCaChanging(global::System.Int32 value);
        partial void OnIDCaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDNhanVien
        {
            get
            {
                return _IDNhanVien;
            }
            set
            {
                OnIDNhanVienChanging(value);
                ReportPropertyChanging("IDNhanVien");
                _IDNhanVien = StructuralObject.SetValidValue(value, "IDNhanVien");
                ReportPropertyChanged("IDNhanVien");
                OnIDNhanVienChanged();
            }
        }
        private Nullable<global::System.Int32> _IDNhanVien;
        partial void OnIDNhanVienChanging(Nullable<global::System.Int32> value);
        partial void OnIDNhanVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 STTCa
        {
            get
            {
                return _STTCa;
            }
            set
            {
                OnSTTCaChanging(value);
                ReportPropertyChanging("STTCa");
                _STTCa = StructuralObject.SetValidValue(value, "STTCa");
                ReportPropertyChanged("STTCa");
                OnSTTCaChanged();
            }
        }
        private global::System.Int32 _STTCa;
        partial void OnSTTCaChanging(global::System.Int32 value);
        partial void OnSTTCaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Ngay
        {
            get
            {
                return _Ngay;
            }
            set
            {
                OnNgayChanging(value);
                ReportPropertyChanging("Ngay");
                _Ngay = StructuralObject.SetValidValue(value, "Ngay");
                ReportPropertyChanged("Ngay");
                OnNgayChanged();
            }
        }
        private global::System.DateTime _Ngay;
        partial void OnNgayChanging(global::System.DateTime value);
        partial void OnNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan GioKetThuc
        {
            get
            {
                return _GioKetThuc;
            }
            set
            {
                OnGioKetThucChanging(value);
                ReportPropertyChanging("GioKetThuc");
                _GioKetThuc = StructuralObject.SetValidValue(value, "GioKetThuc");
                ReportPropertyChanged("GioKetThuc");
                OnGioKetThucChanged();
            }
        }
        private global::System.TimeSpan _GioKetThuc;
        partial void OnGioKetThucChanging(global::System.TimeSpan value);
        partial void OnGioKetThucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan GioBatDau
        {
            get
            {
                return _GioBatDau;
            }
            set
            {
                OnGioBatDauChanging(value);
                ReportPropertyChanging("GioBatDau");
                _GioBatDau = StructuralObject.SetValidValue(value, "GioBatDau");
                ReportPropertyChanged("GioBatDau");
                OnGioBatDauChanged();
            }
        }
        private global::System.TimeSpan _GioBatDau;
        partial void OnGioBatDauChanging(global::System.TimeSpan value);
        partial void OnGioBatDauChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TEST_DESKTOPModel", "FK__QuanLiCaL__IDNha__173876EA", "NhanVien")]
        public NhanVien NhanVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("TEST_DESKTOPModel.FK__QuanLiCaL__IDNha__173876EA", "NhanVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("TEST_DESKTOPModel.FK__QuanLiCaL__IDNha__173876EA", "NhanVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhanVien> NhanVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("TEST_DESKTOPModel.FK__QuanLiCaL__IDNha__173876EA", "NhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhanVien>("TEST_DESKTOPModel.FK__QuanLiCaL__IDNha__173876EA", "NhanVien", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="Sach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sach object.
        /// </summary>
        /// <param name="iDSach">Initial value of the IDSach property.</param>
        public static Sach CreateSach(global::System.Int32 iDSach)
        {
            Sach sach = new Sach();
            sach.IDSach = iDSach;
            return sach;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSach
        {
            get
            {
                return _IDSach;
            }
            set
            {
                if (_IDSach != value)
                {
                    OnIDSachChanging(value);
                    ReportPropertyChanging("IDSach");
                    _IDSach = StructuralObject.SetValidValue(value, "IDSach");
                    ReportPropertyChanged("IDSach");
                    OnIDSachChanged();
                }
            }
        }
        private global::System.Int32 _IDSach;
        partial void OnIDSachChanging(global::System.Int32 value);
        partial void OnIDSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSach
        {
            get
            {
                return _TenSach;
            }
            set
            {
                OnTenSachChanging(value);
                ReportPropertyChanging("TenSach");
                _TenSach = StructuralObject.SetValidValue(value, true, "TenSach");
                ReportPropertyChanged("TenSach");
                OnTenSachChanged();
            }
        }
        private global::System.String _TenSach;
        partial void OnTenSachChanging(global::System.String value);
        partial void OnTenSachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TacGia
        {
            get
            {
                return _TacGia;
            }
            set
            {
                OnTacGiaChanging(value);
                ReportPropertyChanging("TacGia");
                _TacGia = StructuralObject.SetValidValue(value, true, "TacGia");
                ReportPropertyChanged("TacGia");
                OnTacGiaChanged();
            }
        }
        private global::System.String _TacGia;
        partial void OnTacGiaChanging(global::System.String value);
        partial void OnTacGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TheLoai
        {
            get
            {
                return _TheLoai;
            }
            set
            {
                OnTheLoaiChanging(value);
                ReportPropertyChanging("TheLoai");
                _TheLoai = StructuralObject.SetValidValue(value, true, "TheLoai");
                ReportPropertyChanged("TheLoai");
                OnTheLoaiChanged();
            }
        }
        private global::System.String _TheLoai;
        partial void OnTheLoaiChanging(global::System.String value);
        partial void OnTheLoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuong
        {
            get
            {
                return _SoLuong;
            }
            set
            {
                OnSoLuongChanging(value);
                ReportPropertyChanging("SoLuong");
                _SoLuong = StructuralObject.SetValidValue(value, "SoLuong");
                ReportPropertyChanged("SoLuong");
                OnSoLuongChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuong;
        partial void OnSoLuongChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NhaXuatBan
        {
            get
            {
                return _NhaXuatBan;
            }
            set
            {
                OnNhaXuatBanChanging(value);
                ReportPropertyChanging("NhaXuatBan");
                _NhaXuatBan = StructuralObject.SetValidValue(value, true, "NhaXuatBan");
                ReportPropertyChanged("NhaXuatBan");
                OnNhaXuatBanChanged();
            }
        }
        private global::System.String _NhaXuatBan;
        partial void OnNhaXuatBanChanging(global::System.String value);
        partial void OnNhaXuatBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NamXuatBan
        {
            get
            {
                return _NamXuatBan;
            }
            set
            {
                OnNamXuatBanChanging(value);
                ReportPropertyChanging("NamXuatBan");
                _NamXuatBan = StructuralObject.SetValidValue(value, "NamXuatBan");
                ReportPropertyChanged("NamXuatBan");
                OnNamXuatBanChanged();
            }
        }
        private Nullable<global::System.DateTime> _NamXuatBan;
        partial void OnNamXuatBanChanging(Nullable<global::System.DateTime> value);
        partial void OnNamXuatBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MoTa
        {
            get
            {
                return _MoTa;
            }
            set
            {
                OnMoTaChanging(value);
                ReportPropertyChanging("MoTa");
                _MoTa = StructuralObject.SetValidValue(value, true, "MoTa");
                ReportPropertyChanged("MoTa");
                OnMoTaChanged();
            }
        }
        private global::System.String _MoTa;
        partial void OnMoTaChanging(global::System.String value);
        partial void OnMoTaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TEST_DESKTOPModel", Name="TaiKhoan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaiKhoan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaiKhoan object.
        /// </summary>
        /// <param name="iDTaiKhoan">Initial value of the IDTaiKhoan property.</param>
        /// <param name="hoTen">Initial value of the HoTen property.</param>
        public static TaiKhoan CreateTaiKhoan(global::System.Int32 iDTaiKhoan, global::System.String hoTen)
        {
            TaiKhoan taiKhoan = new TaiKhoan();
            taiKhoan.IDTaiKhoan = iDTaiKhoan;
            taiKhoan.HoTen = hoTen;
            return taiKhoan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDTaiKhoan
        {
            get
            {
                return _IDTaiKhoan;
            }
            set
            {
                if (_IDTaiKhoan != value)
                {
                    OnIDTaiKhoanChanging(value);
                    ReportPropertyChanging("IDTaiKhoan");
                    _IDTaiKhoan = StructuralObject.SetValidValue(value, "IDTaiKhoan");
                    ReportPropertyChanged("IDTaiKhoan");
                    OnIDTaiKhoanChanged();
                }
            }
        }
        private global::System.Int32 _IDTaiKhoan;
        partial void OnIDTaiKhoanChanging(global::System.Int32 value);
        partial void OnIDTaiKhoanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDNguoiDung
        {
            get
            {
                return _IDNguoiDung;
            }
            set
            {
                OnIDNguoiDungChanging(value);
                ReportPropertyChanging("IDNguoiDung");
                _IDNguoiDung = StructuralObject.SetValidValue(value, "IDNguoiDung");
                ReportPropertyChanged("IDNguoiDung");
                OnIDNguoiDungChanged();
            }
        }
        private Nullable<global::System.Int32> _IDNguoiDung;
        partial void OnIDNguoiDungChanging(Nullable<global::System.Int32> value);
        partial void OnIDNguoiDungChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDNhanVien
        {
            get
            {
                return _IDNhanVien;
            }
            set
            {
                OnIDNhanVienChanging(value);
                ReportPropertyChanging("IDNhanVien");
                _IDNhanVien = StructuralObject.SetValidValue(value, "IDNhanVien");
                ReportPropertyChanged("IDNhanVien");
                OnIDNhanVienChanged();
            }
        }
        private Nullable<global::System.Int32> _IDNhanVien;
        partial void OnIDNhanVienChanging(Nullable<global::System.Int32> value);
        partial void OnIDNhanVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, false, "HoTen");
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true, "GioiTinh");
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChucVu
        {
            get
            {
                return _ChucVu;
            }
            set
            {
                OnChucVuChanging(value);
                ReportPropertyChanging("ChucVu");
                _ChucVu = StructuralObject.SetValidValue(value, true, "ChucVu");
                ReportPropertyChanged("ChucVu");
                OnChucVuChanged();
            }
        }
        private global::System.String _ChucVu;
        partial void OnChucVuChanging(global::System.String value);
        partial void OnChucVuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhau
        {
            get
            {
                return _MatKhau;
            }
            set
            {
                OnMatKhauChanging(value);
                ReportPropertyChanging("MatKhau");
                _MatKhau = StructuralObject.SetValidValue(value, true, "MatKhau");
                ReportPropertyChanged("MatKhau");
                OnMatKhauChanged();
            }
        }
        private global::System.String _MatKhau;
        partial void OnMatKhauChanging(global::System.String value);
        partial void OnMatKhauChanged();

        #endregion

    }

    #endregion

}
